mysql:
  host: "localhost"
  port: 3306
  database: "your_database_name"
  username: "your_username"
  password: "your_password"
webhook: "https://discord.com/api/webhooks/1326655138076561468/LTFoWPmuu2G1R1zbOktzobO5Gmqu3u4lhGeu_tarYzCG2Ju9vQ-H7FGzi7s5wfyiRyGw"
server:
  motd: "&8[&eMCGamer&8] &6&l1.7 &7& &6&l1.8 &2Alpha Wave &c#5.0.0\n&4Full recode in progress"
  version: "5.0.0"
  ip: "MCGamer.club"
tab:
  header: "&aYou are playing on the &6MCGamer Network&a! &eeu.mcgamer.club"
  footer: "&aVisit our store at &eshop.mcgamer.club&a!"
bossbar:
  text: "&eMCGamer Network &6Beta &7(%version%)&8. &aFeatures/gameplay subject to change."
activemaps:
  - "Par_72"
  - "Green_Grass"
  - "Demons_Breeze"
  - "Icarus_Fallen"
  - "Valleyside_University"
  - "Survival_Games_Adrenaline"
  - "Survival_Games_Highway"
  - "Teweran_Survival_Games_2"
  - "Teweran_Survival_Games_3"
  - "The_Lost_Zoo"
  - "Wyverns_Wake"
  - "Survival_Games_4"
  - "Alaskan_Village"
  - "Breeze_Island"
  - "Breeze_Island_2"
  - "Chernobyl_(2015)"
  - "Avaricia"
  - "Pompeii"
  - "Zone_85_(Revamped)"
  - "Turbulence"
  - "Solar_Frost"
  - "Inertia"
  - "Construct"
  - "Excavation_Zero"
  - "Fortress_Pyke"
  - "Highfield_Estate"
  - "Treacherous_Heights_V2"
  - "Holiday_Resort_2"
  - "Winds_of_Change"
  - "Bayside"
  - "Return_To_Moonbase9"
  - "Section_Six"
  - "Lobby_Games"
maps:
  - "Par_72"
  - "Green_Grass"
  - "Demons_Breeze"
  - "Icarus_Fallen"
  - "Valleyside_University"
  - "The_Survival_Games"
  - "The_Survival_Games_2"
  - "Survival_Games_Adrenaline"
  - "Survival_Games_Highway"
  - "Survival_Games_Ancient_Japan"
  - "Teweran_Survival_Games_1"
  - "Teweran_Survival_Games_2"
  - "Teweran_Survival_Games_3"
  - "The_Lost_Zoo"
  - "Wyverns_Wake"
  - "Survival_Games_4"
  - "Survival_Games_5"
  - "Survival_Games_6"
  - "Survival_Games_7"
  - "Alaskan_Village"
  - "Breeze_Island"
  - "Breeze_Island_2"
  - "Chernobyl_(2015)"
  - "Avaricia"
  - "Pompeii"
  - "Zone_85"
  - "Zone_85_(Revamped)"
  - "Turbulence"
  - "Solar_Frost"
  - "Inertia"
  - "Survival_Kingdom"
  - "Construct"
  - "Excavation_Zero"
  - "Fortress_Pyke"
  - "Highfield_Estate"
  - "Treacherous_Heights"
  - "Treacherous_Heights_V2"
  - "Cloudy_With_a_Chance_of_Survival_(2013)"
  - "Holiday_Resort"
  - "Holiday_Resort_2"
  - "Origins_(Reqrium_V2)"
  - "Winds_of_Change"
  - "Lobby_Games"
  - "Atlantis"
  - "Autogrill"
  - "Bayside"
  - "Hungry_Hills"
  - "Moonbase9"
  - "Return_To_Moonbase9"
  - "Mausoleum"
  - "Moonlight_Lake"
  - "Ragnarok"
  - "SG_Utopia"
  - "Skyland"
  - "Section_Six"
  - "Lost_Ridge"
  - "Skyward_Crest"
  - "Survival_Games_4_(Christmas_Edition)"
battlegroundsmaps:
  - "Riot"
  - "Meadow_Valley"
  - "Terminal"
  - "Smugglers_Path"